apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mosquitto-bridge.fullname" . }}-cm-mosquitto-conf
  labels:
    app: mqtt-broker
  {{- include "mosquitto-bridge.labels" . | nindent 4 }}
data:
  mosquitto.conf: {{ .Values.cmMosquittoConf.mosquittoConf | toYaml | indent 1 }}
  mosquitto.passwd: {{ .Values.cmMosquittoConf.mosquittoPasswd | toYaml | indent
    1 }}