apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mosquitto-bridge.fullname" . }}-mqtt-broker
  labels:
    app: mqtt-broker
  {{- include "mosquitto-bridge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mqttBroker.replicas }}
  selector:
    matchLabels:
      app: mqtt-broker
    {{- include "mosquitto-bridge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mqtt-broker
      {{- include "mosquitto-bridge.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.mqttBroker.mqttBroker.image.repository }}:{{ .Values.mqttBroker.mqttBroker.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.mqttBroker.mqttBroker.imagePullPolicy }}
        name: mqtt-broker
        ports:
        - containerPort: 1883
        - containerPort: 9001
        resources: {}
        volumeMounts:
        - mountPath: /mosquitto/config
          name: config-file
        - mountPath: /mosquitto/data
          name: data-volume
      hostNetwork: true
      restartPolicy: Always
      securityContext:
        runAsUser: 0
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: {{ include "mosquitto-bridge.fullname" . }}-pvc-mqtt
      - configMap:
          name: {{ include "mosquitto-bridge.fullname" . }}-cm-mosquitto-conf
        name: config-file