apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto-bridge.fullname" . }}-mqtt-broker-service
  labels:
  {{- include "mosquitto-bridge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mqttBrokerService.type }}
  selector:
    app: mqtt-broker
  {{- include "mosquitto-bridge.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.mqttBrokerService.ports | toYaml | nindent 2 }}