apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "mosquitto-bridge.fullname" . }}-pv-mqtt
  labels:
  {{- include "mosquitto-bridge.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200M
  claimRef:
    name: pvc-mqtt
    namespace: mqtt
  hostPath:
    path: /opt/mosquitto